version: '3'

networks:
  monitor:

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - monitor
