version: '3'

networks:
  loki:

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - loki

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - loki

  loki:
    image: grafana/loki:2.3.0
    volumes:
      - /opt/loki/configuation/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /opt/promtail/configuation/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /home/eduvalor371/backend_eduvalor/logs:/var/log
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - loki
